# Generated by Django 2.0.4 on 2018-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_department_patient_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='PatID',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='_time',
            field=models.CharField(max_length=5),
        ),
    ]
