# Generated by Django 2.0.4 on 2018-07-06 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20180519_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medHistory', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='_time',
        ),
        migrations.AddField(
            model_name='department',
            name='depart_id',
            field=models.IntegerField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='describe',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='describe',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dor_id',
            field=models.IntegerField(default=1001, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='MedcardID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='idnumber',
            field=models.IntegerField(default=500000000000000, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='tel_num',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='PatID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myweb.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='month',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medcard',
            name='PatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Patient'),
        ),
    ]
