# Generated by Django 2.0.4 on 2018-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20180706_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='describe',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
